### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by jossie67** [robgeerts/Dashticz#20] opened 2015-02-20 13:32 UTC
Hi 
I have copied versie 0.73 into de folder /dash, I change some settings.
After that I have a blank screen, with only dashticz v0.73 Domticz  on the top.
I removed all the files in de folder /dash and copied all the file source back in the folder.
Still my screen is black, How can I reset Dashticz

**Comment by robgeerts** [comment] 2015-02-20 13:34
Could you give me a screendump of your settings screen?

**Comment by jossie67** [comment] 2015-02-20 16:56
Rob,

is this what you mean


![knipsel](https://cloud.githubusercontent.com/assets/10726261/6305215/c4c9a0a8-b929-11e4-81aa-d288fc9f49a2.JPG)

**Comment by robgeerts** [comment] 2015-02-20 16:58
Yes!
Remove /index.html from the Domoticz-path...

**Comment by jossie67** [comment] 2015-02-20 18:18
When I remove /index.html and press Opslaan.
The instelling page closes when I then reopen instelling /index.html is back :-(
Even when remove the complet folder and reinstall Dashticz all the settings are there

**Comment by robgeerts** [comment] 2015-02-20 18:21
Thats because settings are save inside Domoticz (uservariables / gebruikersvariabelen).
I will look at the problem settings arent saved correct, in the meantime, you can edit this setting on:
http://192.168.10.33:8080/#/UserVariables

**Comment by Brutuss** [comment] 2015-02-20 18:22
When you connect to Domoticz from this PC do you need to login? If so you need to change the url a bit so Dashticz can login for you. Change the password and username to yours.

http://username:password@192.168.10.33:8080

**Comment by robgeerts** [comment] 2015-02-20 20:48
Otherwise, try the latest version (0.79) en edit the path to Domoticz in CONFIG.js

**Comment by bizziebis** [comment] 2015-02-21 21:45
Maybe it's because there is missing a declaration of a variable in CONFIG.js:

var _HOST_PLEX          = '';

**Comment by robgeerts** [comment] 2015-02-21 21:50
No, that declaration has been added in the latest version wich he isn't using yet.
You could always check in your console in the webbrowser for javascript-errors... Do you see any?

**Comment by robgeerts** [comment] 2015-02-23 21:28
I have added a check for the config-variables, if it doesn't exists it wont crash. But @jossie67, does the problem still exists?

**Comment by blondophile** [comment] 2015-02-26 16:03
Hi,  I am running Domoticz on a PI, and I have tried to install your dashboard on my synology, add the right var_host... for domoticz but the page is blank (with "Dashticz" browser 's title) 
I've also tried to copy the dashticz folder into the WWW of domoticz but same behavior.
Maybe I am missing an Apache module ? 
Any idea, have I missed something ?

**Comment by robgeerts** [comment] 2015-02-26 16:15
Could you open the 'console'-window of your webbrowser to check if there are any javascript-errors?

**Comment by blondophile** [comment] 2015-02-26 16:23
There is :
https://interyield.jmp9.com/InterYield/bindevent.do?e=click&affiliate=alexwebstore&subid=nosubid&ecpm=0&debug=false&snoozeMinutes=300&adCountIntervalHours=24&maxAdCountsPerInterval=2&attributionLogo=custom+attribution&attributionTitle=custom+attribution+title&attributionLink=custom+attribution+link

Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

and

http://admin:*********@192.168.0.16:8080/json.htm?type=command&param=getSunRiseSet&jsoncallback=jQuery21305101970694959164_1424965474183&_=1424965474184

 Failed to load resource: net::ERR_CONNECTION_TIMED_OUT

**Comment by robgeerts** [comment] 2015-02-26 16:25
Well, the first one is not used by Dashticz, so that may be a resource from a previous website or addon in your webbrowser. For the second one: it says it cannot reach Domoticz.

What do you see when you copy that url directly to your webbrowser?

**Comment by robgeerts** [comment] 2015-02-26 16:27
Oh, and could you try to remove the security? 
Temporarily...

**Comment by blondophile** [comment] 2015-02-26 16:29
I am currently with the security login page and I have tried basic auth and no security...
Same behaviour :(

**Comment by robgeerts** [comment] 2015-02-26 16:31
Ok, but what response do you get when you enter:

http://admin:PASSWORD@192.168.0.16:8080/json.htm?type=command&param=getSunRiseSet&jsoncallback=jQuery21305101970694959164_1424965474183&_=1424965474184 

directly in your webbrowser?

**Comment by blondophile** [comment] 2015-02-26 19:38
I have started domoticz with -nowwwpwd  and tried again with no password and I am getting : 
var data={ "ServerTime" : "Feb 26 2015 20:33:07", "Sunrise" : "07:39:00", "Sunset" : "18:26:00", "status" : "OK", "title" : "getSunRiseSet" } jQuery21305101970694959164_1424965474183(data);
no console error but still blank

**Comment by robgeerts** [comment] 2015-02-26 19:39
Ok, do you have Teamviewer installed, that way I can solve your problem...

**Comment by robgeerts** [comment] 2015-02-26 19:56
I have pushed a new version. 
I just tested with and without a secured Domoticz, both worked, so it's hard for me to understand what the problem is. Could you see what's the last http-call Dashticz makes? (In the console-window, there's a Netwerk-tab).

**Comment by blondophile** [comment] 2015-02-26 20:16
Hi doing a Ctrl + F5 in chrome I got this :
jquery.js:8625 XHR finished loading: GET "http://192.168.0.199/Dashticz/CONFIG.js?_=1424981571045".jquery.js:8625 XHR finished loading: GET "http://192.168.0.199/Dashticz/js/functions.js?_=1424981571046".jquery.js:8693 Resource interpreted as Script but transferred with MIME type text/html: "http://192.168.0.16:8080/json.htm?type=command&param=getSunRiseSet&jsoncallback=jQuery21309750287011265755_1424981571047&_=1424981571048".bindevent.do?e=click&affiliate=alexwebstore&subid=nosubid&ecpm=0&debug=false&snoozeMinutes=300&adCo…:6 InterYield click bind handler snoozes.jquery.js:8625 XHR finished loading: GET "http://192.168.0.199/Dashticz/js/languages/en_US.js?_=1424981571050".jquery.js:8693 Resource interpreted as Script but transferred with MIME type text/html: "http://192.168.0.16:8080/json.htm?type=command&param=getuservariables&jsoncallback=jQuery21309750287011265755_1424981571047&_=1424981571049".jquery.js:8625 XHR finished loading: GET "http://192.168.0.199/Dashticz/js/blocks.js?_=1424981571052".jquery.js:8625 XHR finished loading: GET "http://192.168.0.199/Dashticz/apps/kodi/kodi.js?_=1424981571051"

Date: Thu, 26 Feb 2015 11:56:14 -0800

**Comment by robgeerts** [comment] 2015-02-26 20:21
It's seems you have some malware on your pc wich manipulates the calls. The call with 'getSunriseSet' is extended with sme affiliate-code (affiliate=alexwebstore).

A search on the internet gives me the following, possible, solution: 
"The only thing similar with all the users is the InterYield Click Bind in their Console logging. I had them run a Malware scanner (Malwarebytes Anti-Malware works best), and after it cleans the system, they are able to access the sites."

**Comment by jossie67** [comment] 2015-03-03 12:03
Rob, sorry I was on ski holiday. I reinstalled Dashticz and edited /#/UserVariables.
It seems to work again.

**Comment by robgeerts** [comment] 2015-03-03 14:08
Nice!

**Closed by robgeerts** 2015-03-03 14:08 UTC
Labels: bug
